spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:tcp://localhost/~/MovieTheater
    username: sa
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

